# .readthedocs.yml

version: 2

sphinx:
  configuration: docs/conf.py

python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

build:
  jobs:
    post_install:
      - sphinx-apidoc -o docs -t docs/_templates -T --extensions sphinx.ext.doctest,sphinx.ext.mathjax,sphinx.ext.autosectionlabel,myst_parser,sphinx.ext.todo -d 3 -E -f -F python/dfisher_2022a
