# .readthedocs.yml
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"
  jobs:
    post_create_environment:
      # Install poetry; see https://python-poetry.org/docs/
      - curl -sSL https://install.python-poetry.org | python3 -
      # Tell poetry to not use a virtual environment
      # - $HOME/.local/bin/poetry config virtualenvs.create false
      # Install project's dependencies
      - $HOME/.local/bin/poetry install -E docs

    post_install:
      - make apidoc

sphinx:
  configuration: docs/conf.py
