# .readthedocs.yml
version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
      - poetry config virtualenvs.create false
    post_create_environment:
      - poetry install --no-dev -E docs
    post_install:
      - make apidoc
sphinx:
  configuration: docs/conf.py
