[tool.poetry]
name = "lorikeet"
version = "0.1.0"
description = "Spectral analysis code created for the delivery of the DFisher_2022A ADACS MAP project."
authors = ["Gregory Poole <gbpoole@gmail.com>"]
license = "MIT-expat"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
