name: Publish

on:
  release:
    types: [created]

jobs:
  initialise:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install basic dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install poetry

  run-tests:
    runs-on: ubuntu-latest
    needs: initialise

    steps:
    - uses: actions/checkout@v2

    - name: Generate build
      run: |
        poetry version $(git describe --tags --abbrev=0)
        poetry build

    - name: Code tests
      run: |
        pytest

    - name: Documentation build test
      run: |
        poetry install --extras docs
        make html

  publish-code:
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
    - uses: actions/checkout@v2

    - name: Publish to PyPI
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_RTD_TOKEN }}
        poetry publish

  publish-docs:
    runs-on: ubuntu-latest
    needs: publish-code

    steps:
    - uses: actions/checkout@v2

    - name: Trigger RTDs build
      run: |
        curl -X POST                                                    \
             -H "Authorization: Token ${{ secrets.RTD_WEBHOOK_TOKEN }}" \
             ${{ secrets.RTD_WEBHOOK_URL_DFISHER_2022A }}
